name: "deploy"
on:
    push:
        branches:
            - main

jobs:
    build_ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'recursive'
            - name: Setup SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                port: 22
                script: |
                    cd /drawn-frontend
                    git pull
                    bun install
                    bun run build
                    pm2 restart drawn_frontend

                    